# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField(default=0)),
                ('home_address', models.CharField(max_length=300)),
                ('phone', models.IntegerField(default=0)),
                ('hobbies', models.CharField(max_length=400)),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=b'icon/', verbose_name=b'profile', width_field=b'width_field')),
            ],
        ),
    ]
