# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
