# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_profile_relationship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ContactDetails',
        ),
    ]
