# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180227_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='relationship',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
