# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180227_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
