# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180227_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
