# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_contactdetails_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=menu.models.upload_location, width_field=b'width_field'),
        ),
    ]
