# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_contactdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
