# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20180324_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='slug',
            field=models.SlugField(blank=True, default=0, null=True),
        ),
    ]
