# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20180325_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
