# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import facescan.models


class Migration(migrations.Migration):

    dependencies = [
        ('facescan', '0003_auto_20180301_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=facescan.models.upload_location, width_field='width_field'),
        ),
    ]
