# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facescan', '0004_auto_20180301_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='item',
            name='excludes',
        ),
    ]
